/**
 * Shared Config — loads from packages/sdk/config.json with hardcoded fallbacks.
 *
 * Dynamically reads deployed contract addresses, HCS topics, iNFT collection IDs,
 * and vault parameters from the SDK config generated by deploy scripts.
 * Falls back to hardcoded values if the file is missing (e.g., in test envs).
 */

import { config as dotenvConfig } from "dotenv";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { readFileSync, existsSync } from "fs";

const __configDir = dirname(fileURLToPath(import.meta.url));
dotenvConfig({ path: join(__configDir, "..", ".env") });

// ─── Load SDK config.json ──────────────────────────────────────────────────

const SDK_CONFIG_PATH = join(__configDir, "..", "..", "packages", "sdk", "config.json");

interface SdkConfig {
  guardTokenId?: string;
  guardTokenEvmAddress?: string;
  hcsTopics?: { discovery?: string; auditLog?: string; agentComms?: string };
  contracts?: Record<string, { id?: string; evmAddress?: string }>;
  inftCollections?: Record<string, { tokenId?: string; evmAddress?: string }>;
  demoVault?: { contractAddress?: string; weeklyMonitoring?: number; criticalBounty?: number };
  day2?: { settlementPreFunded?: number; deployedAt?: string };
}

function loadSdkConfig(): SdkConfig | null {
  try {
    if (!existsSync(SDK_CONFIG_PATH)) return null;
    return JSON.parse(readFileSync(SDK_CONFIG_PATH, "utf-8"));
  } catch {
    return null;
  }
}

const sdk = loadSdkConfig();

// ─── Build CONFIG — SDK values override hardcoded defaults ─────────────────

export const CONFIG = {
  network: "testnet" as const,

  guardToken: {
    id: sdk?.guardTokenId ?? "0.0.7936262",
    evmAddress: sdk?.guardTokenEvmAddress ?? "0x0000000000000000000000000000000000791906",
  },

  hcsTopics: {
    discovery: sdk?.hcsTopics?.discovery ?? "0.0.7940144",
    auditLog: sdk?.hcsTopics?.auditLog ?? "0.0.7940145",
    agentComms: sdk?.hcsTopics?.agentComms ?? "0.0.7940146",
  },

  contracts: {
    agentRegistry: sdk?.contracts?.agentRegistry?.evmAddress ?? "0xe86218b5Bf5C21CA7a69cba04C5be0D3c2Be2303",
    budgetVault: sdk?.contracts?.budgetVault?.evmAddress ?? "0x68780A12b36f3ed04CEF937EFc38b593683c5fCd",
    auction: (sdk?.contracts?.auctionContract?.evmAddress ?? sdk?.contracts?.auction?.evmAddress) ?? "0x95A0A0e78a32c849526d6AC32e98c6829FB2Cd88",
    subAuction: sdk?.contracts?.subAuction?.evmAddress ?? "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    dataMarketplace: sdk?.contracts?.dataMarketplace?.evmAddress ?? "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    paymentSettlement: sdk?.contracts?.paymentSettlement?.evmAddress ?? "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
  },

  inftCollections: {
    auditJob: {
      tokenId: sdk?.inftCollections?.auditJob?.tokenId ?? "0.0.7946509",
      evmAddress: sdk?.inftCollections?.auditJob?.evmAddress ?? "",
    },
    agentProfile: {
      tokenId: sdk?.inftCollections?.agentProfile?.tokenId ?? "0.0.7946510",
      evmAddress: sdk?.inftCollections?.agentProfile?.evmAddress ?? "",
    },
    contractHealth: {
      tokenId: sdk?.inftCollections?.contractHealth?.tokenId ?? "0.0.7946511",
      evmAddress: sdk?.inftCollections?.contractHealth?.evmAddress ?? "",
    },
  },

  // Demo/test params
  settlementPreFunded: sdk?.day2?.settlementPreFunded ?? 500,
  demoVault: {
    address: sdk?.demoVault?.contractAddress ?? "0x000000000000000000000000000000000000dEaD",
    weeklyMonitoring: sdk?.demoVault?.weeklyMonitoring ?? 10,
    criticalBounty: sdk?.demoVault?.criticalBounty ?? 50,
  },

  // 0g Compute Network inference config (uses @0glabs/0g-serving-broker SDK)
  zgInference: {
    rpcUrl: process.env.ZG_RPC_URL ?? "https://evmrpc-testnet.0g.ai",
    providerAddress: process.env.ZG_PROVIDER_ADDRESS ?? "",
    model: process.env.ZG_MODEL ?? "qwen-2.5-7b-instruct",
    timeoutMs: Number(process.env.ZG_TIMEOUT_MS ?? "30000"),
    depositAmount: Number(process.env.ZG_DEPOSIT_AMOUNT ?? "5"),
    enabled: process.env.ZG_ENABLED !== "false",
  },
} as const;

/** Path to the SDK config.json for direct reading (used by INFTBridge). */
export const SDK_CONFIG_FILE = SDK_CONFIG_PATH;

// Per-agent env vars — fill in .env
export function getAgentEnv(agentName: string) {
  const prefix = agentName.toUpperCase();
  const accountId = process.env[`${prefix}_ACCOUNT_ID`] || process.env.OPERATOR_ACCOUNT_ID;
  const privateKey = process.env[`${prefix}_PRIVATE_KEY`] || process.env.OPERATOR_PRIVATE_KEY;

  if (!accountId || !privateKey) {
    throw new Error(
      `Missing credentials for agent "${agentName}". ` +
      `Set ${prefix}_ACCOUNT_ID/${prefix}_PRIVATE_KEY or OPERATOR_ACCOUNT_ID/OPERATOR_PRIVATE_KEY in .env`
    );
  }

  return { accountId, privateKey };
}
