// JS companion for runtime ESM imports from orchestrator.
export const MessageType = {
  CONTRACT_DISCOVERED: "CONTRACT_DISCOVERED",
  SUB_AUCTION_POSTED: "SUB_AUCTION_POSTED",
  SUB_RESULT_DELIVERED: "SUB_RESULT_DELIVERED",
  DATA_LISTING_CREATED: "DATA_LISTING_CREATED",
  FINDINGS_SUBMITTED: "FINDINGS_SUBMITTED",
  AGENT_REGISTERED: "AGENT_REGISTERED",
  PING: "PING",
  PONG: "PONG",
  AUCTION_INVITE: "AUCTION_INVITE",
  BID_SUBMITTED: "BID_SUBMITTED",
  BID_SKIPPED: "BID_SKIPPED",
  BID_SUBMISSION_FAILED: "BID_SUBMISSION_FAILED",
  AUCTION_INVITE_SUMMARY: "AUCTION_INVITE_SUMMARY",
  LLM_PROVIDER_READY: "LLM_PROVIDER_READY",
  LLM_PROVIDER_UNHEALTHY: "LLM_PROVIDER_UNHEALTHY",
  LLM_INFERENCE_STARTED: "LLM_INFERENCE_STARTED",
  LLM_INFERENCE_SUCCEEDED: "LLM_INFERENCE_SUCCEEDED",
  LLM_INFERENCE_FAILED: "LLM_INFERENCE_FAILED",
  WINNERS_SELECTED_FALLBACK: "WINNERS_SELECTED_FALLBACK",
  AUDIT_LOG: "AUDIT_LOG",
  REPUTATION_UPDATED: "REPUTATION_UPDATED",
};

export function now() {
  return Date.now();
}
