// JS companion for runtime ESM imports from orchestrator.
export const MessageType = {
  CONTRACT_DISCOVERED: "CONTRACT_DISCOVERED",
  SUB_AUCTION_POSTED: "SUB_AUCTION_POSTED",
  SUB_RESULT_DELIVERED: "SUB_RESULT_DELIVERED",
  DATA_LISTING_CREATED: "DATA_LISTING_CREATED",
  FINDINGS_SUBMITTED: "FINDINGS_SUBMITTED",
  AGENT_REGISTERED: "AGENT_REGISTERED",
  PING: "PING",
  PONG: "PONG",
  AUCTION_INVITE: "AUCTION_INVITE",
  WINNERS_SELECTED_FALLBACK: "WINNERS_SELECTED_FALLBACK",
  AUDIT_LOG: "AUDIT_LOG",
  REPUTATION_UPDATED: "REPUTATION_UPDATED",
};

export function now() {
  return Date.now();
}
