/**
 * Offline replay service
 *
 * Loads /offline-state.json generated by orchestrator offline tests and
 * hydrates the dashboard store, so "fake live" auctions/reports are visible.
 */

function hydrateStore(store, snapshot) {
  if (!snapshot || typeof snapshot !== 'object') return;

  store.resetAll?.();

  // Agents first so cards/resolvers have identities.
  for (const [addr, profile] of Object.entries(snapshot.agents || {})) {
    store.setAgent?.(addr, profile);
  }

  for (const d of snapshot.discoveries || []) {
    store.addDiscovery?.(d);
  }

  for (const [jobId, job] of Object.entries(snapshot.activeJobs || {})) {
    store.setJob?.(jobId, job);
  }

  for (const [jobId, bids] of Object.entries(snapshot.bids || {})) {
    for (const bid of bids || []) {
      store.addBid?.(jobId, bid);
    }
  }

  for (const [jobId, winners] of Object.entries(snapshot.winners || {})) {
    store.setWinners?.(jobId, winners);
  }

  for (const settlement of snapshot.settlements || []) {
    store.addSettlement?.(settlement);
  }

  for (const entry of snapshot.auditLog || []) {
    store.addLogEntry?.(entry);
  }

  const stats = snapshot.stats || {};
  for (const [k, v] of Object.entries(stats)) {
    if (typeof v === 'number' && v > 0) store.incrementStat?.(k, v);
  }
}

export function startOfflineReplay(getState) {
  let lastGeneratedAt = 0;
  let timer = null;
  let stopped = false;

  const load = async () => {
    if (stopped) return;
    try {
      const res = await fetch(`/offline-state.json?ts=${Date.now()}`, { cache: 'no-store' });
      if (!res.ok) return;
      const snapshot = await res.json();
      const generatedAt = Number(snapshot?.generatedAt || 0);
      if (!generatedAt || generatedAt === lastGeneratedAt) return;

      lastGeneratedAt = generatedAt;
      hydrateStore(getState(), snapshot);
      console.log(`[offline-replay] loaded snapshot generatedAt=${generatedAt}`);
    } catch {
      // silent in loop; file may not exist yet
    }
  };

  load();
  timer = setInterval(load, 3000);

  return () => {
    stopped = true;
    if (timer) clearInterval(timer);
  };
}

