import { ipfsGatewayUrl, uploadToIPFS } from "./shared/ipfs-client.js";
import {
  ensureHttpReachableOrSkip,
  ensureToggleOrSkip,
} from "./scripts/live-preflight.js";

async function main(): Promise<void> {
  ensureToggleOrSkip("RUN_LIVE_IPFS_TESTS", "IPFS live tests");
  const ipfsApi = process.env.IPFS_API_URL ?? "http://127.0.0.1:5001";
  const ipfsGateway = process.env.IPFS_GATEWAY_URL ?? "http://127.0.0.1:8080";
  await ensureHttpReachableOrSkip(ipfsApi, "IPFS API");
  await ensureHttpReachableOrSkip(ipfsGateway, "IPFS gateway");

  const testContent = `
# AuditGuard Test Report

## Contract Analyzed
- Address: 0x1234567890abcdef1234567890abcdef12345678
- Type: ERC-20 Token

## Findings
- Critical: No reentrancy guard found
- High: Missing access control

Generated by AuditGuard test-ipfs.ts
`.trim();

  console.log("Uploading to IPFS...");
  const cid = await uploadToIPFS(testContent);
  const url = ipfsGatewayUrl(cid);

  console.log("Upload successful!");
  console.log("CID:", cid);
  console.log("Gateway URL:", url);

  console.log("\nVerifying upload...");
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Gateway fetch failed (${response.status})`);
  }
  const retrieved = await response.text();
  console.log("Retrieved content length:", retrieved.length, "chars");

  if (!retrieved.includes("AuditGuard Test Report")) {
    throw new Error("IPFS verification failed: content marker not found");
  }
  console.log("IPFS upload verified successfully");
}

main().catch((err) => {
  console.error("IPFS test failed:", err);
  process.exit(1);
});
