// Envelope for all HCS messages
export const MessageType = {
  CONTRACT_DISCOVERED: "CONTRACT_DISCOVERED",
  AGENT_REGISTERED: "AGENT_REGISTERED",
  PING: "PING",
  PONG: "PONG",
  FINDINGS_SUBMITTED: "FINDINGS_SUBMITTED",
  DATA_LISTING_CREATED: "DATA_LISTING_CREATED",
  SUB_AUCTION_POSTED: "SUB_AUCTION_POSTED",
  WINNERS_SELECTED_FALLBACK: "WINNERS_SELECTED_FALLBACK",
  AUDIT_LOG: "AUDIT_LOG",
};

export function now() {
  return Date.now();
}
